name: auge_shared
description: Auge shared.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  #angular_router: ^2.0.0-alpha+24
  #html: ^0.14.0+3
  intl: ^0.16.1
  fixnum: ^0.10.11
  protobuf: ^1.1.0
  grpc: ^2.8.0

dev_dependencies:
  intl_translation: ^0.17.10+1
  test: ^1.15.7

executables:
  protoc-gen-dart: protoc_plugin